import type { Knex } from 'knex';

export const seedAiModules = async (knex: Knex): Promise<void> => {
  const exists = await knex('ai_modules').first();
  if (exists) {
    console.log('  ⏩ ai_modules already seeded');
    return;
  }
  
  await knex('ai_modules').insert([
    // === COMPUTE (foundational) ===
    {
      code: 'gpu_v1',
      name: 'GPU V1',
      description: 'Le calcul de base pour ton IA',
      category: 'compute',
      base_cost: 100,
      cost_multiplier: 1.5,
      coins_per_hour_bonus: 50,
      rarity: 'common',
      display_order: 1,
    },
    {
      code: 'gpu_v2',
      name: 'GPU V2',
      description: 'Plus rapide que V1, 5x la puissance',
      category: 'compute',
      base_cost: 1000,
      cost_multiplier: 1.5,
      coins_per_hour_bonus: 250,
      min_ai_level: 5,
      required_module_code: 'gpu_v1',
      rarity: 'common',
      display_order: 2,
    },
    {
      code: 'gpu_v3',
      name: 'GPU V3',
      description: 'GPU haut de gamme, performances débloquées',
      category: 'compute',
      base_cost: 10000,
      cost_multiplier: 1.6,
      coins_per_hour_bonus: 1000,
      min_ai_level: 15,
      required_module_code: 'gpu_v2',
      rarity: 'rare',
      display_order: 3,
    },
    {
      code: 'cluster',
      name: 'Cluster de calcul',
      description: 'Plusieurs GPUs en parallèle',
      category: 'compute',
      base_cost: 50000,
      cost_multiplier: 1.7,
      coins_per_hour_bonus: 5000,
      min_ai_level: 25,
      required_module_code: 'gpu_v3',
      rarity: 'epic',
      display_order: 4,
    },
    
    // === SPECIALTIES (déblocages de quêtes) ===
    {
      code: 'nlp_module',
      name: 'Module NLP',
      description: 'Ton IA apprend à comprendre et générer du texte',
      category: 'specialty',
      base_cost: 5000,
      cost_multiplier: 1.7,
      coins_per_hour_bonus: 500,
      min_ai_level: 5,
      rarity: 'rare',
      display_order: 10,
    },
    {
      code: 'vision_module',
      name: 'Module Vision',
      description: 'Ton IA apprend à voir et reconnaître les images',
      category: 'specialty',
      base_cost: 8000,
      cost_multiplier: 1.7,
      coins_per_hour_bonus: 800,
      min_ai_level: 7,
      rarity: 'rare',
      display_order: 11,
    },
    {
      code: 'code_module',
      name: 'Module Code',
      description: 'Ton IA apprend à écrire et débugger du code',
      category: 'specialty',
      base_cost: 12000,
      cost_multiplier: 1.8,
      coins_per_hour_bonus: 1200,
      min_ai_level: 10,
      rarity: 'epic',
      display_order: 12,
    },
    {
      code: 'voice_module',
      name: 'Module Voice',
      description: 'Ton IA apprend à comprendre et synthétiser la voix',
      category: 'specialty',
      base_cost: 15000,
      cost_multiplier: 1.8,
      coins_per_hour_bonus: 1500,
      min_ai_level: 12,
      rarity: 'epic',
      display_order: 13,
    },
    {
      code: 'reasoning_module',
      name: 'Module Raisonnement',
      description: 'Ton IA apprend à raisonner logiquement',
      category: 'specialty',
      base_cost: 30000,
      cost_multiplier: 1.9,
      coins_per_hour_bonus: 3000,
      min_ai_level: 20,
      rarity: 'legendary',
      display_order: 14,
    },
    
    // === DATASETS (augmente les récompenses) ===
    {
      code: 'dataset_wikipedia',
      name: 'Dataset Wikipedia',
      description: '15M articles, augmente la culture générale',
      category: 'dataset',
      base_cost: 3000,
      cost_multiplier: 1.5,
      coins_per_hour_bonus: 300,
      min_ai_level: 3,
      rarity: 'common',
      display_order: 20,
    },
    {
      code: 'dataset_arxiv',
      name: 'Dataset ArXiv',
      description: '2M papers scientifiques, l\'IA devient brillante',
      category: 'dataset',
      base_cost: 8000,
      cost_multiplier: 1.6,
      coins_per_hour_bonus: 800,
      min_ai_level: 8,
      rarity: 'rare',
      display_order: 21,
    },
    {
      code: 'dataset_github',
      name: 'Dataset GitHub',
      description: 'Des millions de repos, l\'IA apprend à coder',
      category: 'dataset',
      base_cost: 20000,
      cost_multiplier: 1.7,
      coins_per_hour_bonus: 2000,
      min_ai_level: 15,
      rarity: 'epic',
      display_order: 22,
    },
    
    // === ALGORITHMS (boosts divers) ===
    {
      code: 'algorithm_optimizer',
      name: 'Algorithme d\'optimisation',
      description: 'Réduit le coût en énergie de 20%',
      category: 'algorithm',
      base_cost: 5000,
      cost_multiplier: 1.6,
      energy_regen_bonus: 1,
      min_ai_level: 5,
      rarity: 'rare',
      display_order: 30,
    },
    {
      code: 'algorithm_transformer',
      name: 'Algorithme Transformer',
      description: 'Architecture de pointe, +30% sur tous les gains',
      category: 'algorithm',
      base_cost: 25000,
      cost_multiplier: 1.7,
      tap_multiplier_bonus: 1.3,
      min_ai_level: 15,
      rarity: 'epic',
      display_order: 31,
    },
    
    // === THE GRAIL ===
    {
      code: 'gpt_core',
      name: 'GPT Core',
      description: 'Le saint graal. Ton IA devient une AGI.',
      category: 'compute',
      base_cost: 1000000,
      cost_multiplier: 2.0,
      coins_per_hour_bonus: 50000,
      max_level: 1,
      min_ai_level: 50,
      required_module_code: 'reasoning_module',
      rarity: 'legendary',
      display_order: 99,
    },
  ]);
  
  console.log('  ✅ ai_modules seeded (16 modules)');
};
